language: python

python:
  - '2.7'

install:
  - sudo apt-get install -y python-setuptools python-dev libxml2-dev libxslt-dev python-pip
  - pip install -r requirements.txt

script:
  - python tests/test_offline.py
